### ISSUE TITLE
COWorkflowBasePlugin Download?

### ISSUE THREAD

**Issue by Toseph** [DKFZ-ODCF/ACEseqWorkflow#11]
The first part of the guide mentions the following: "Download the COWorkflowBasePlugin zip-archive from Github-Releases. The version to download can be found in the ACEseq buildinfo.txt."

However, this file does not exist in your repo. The .zip and the tarball are both the same.
Can you please upload it, as it does not seem to be available elsewhere. 

Just to be clear, COWorkflowBasePlugin doesn't exist on this repo, the buildinfo.txt does. 

Many thanks,
Toseph

**Comment by dankwart-de** [comment]
Hi Toseph,

you're right, the base plugin does not reside in the same repo as ACEseq. It can be found in its own repo here: https://github.com/TheRoddyWMS/COWorkflowsBasePlugin
The buildinfo.txt file effectively contains the dependencies for ACEseq. 
To run ACEseq, you also need Roddy (also found in TheRoddyWMS). 

Please see the Roddy docs under https://roddy-documentation.readthedocs.io/ to find more information about settings things up. If you need further help, please contact us again.

Best
Michael
